#!/usr/bin/env bash

shopt -s dotglob
targets=$(realpath ~/dotfiles/files/*)

# install symlinks
echo 'Adding symlinks...'
ln -vsf $targets $HOME

# install bash aliases
if test -f ~/.bash_aliases; then
  if ! grep -q 'source ~/.bash_aliases' ~/.bashrc; then
    echo 'Installing bash aliases'
    printf '\n# custom aliases' >> /.bashrc
    printf 'source ~/.bash_aliases' >> ~/.bashrc
  fi
fi
