#!/usr/bin/env bash

set -eo pipefail

if ! test -d ~/dotfiles; then
	git clone https://github.com/ripvannwinkler/dotfiles.git ~/dotfiles
else
	pushd ~/dotfiles
	git pull --rebase
	popd
fi

bash ~/dotfiles/install
