alias ..='cd ..'
alias ll='ls -alh --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias sha1='openssl sha1'
alias sha256='openssl sha256'
alias mkdir='mkdir -pv'
alias vi='vim'
alias edit='vim'
alias ports='netstat -tulanp'
alias wget='wget -c'

alias df='df -H'
alias du='du -ch'
alias top='atop'
